apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backend-secrets
  namespace: lost-university
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  target:
    template:
      data:
        CLERK_PUBLISHABLE_KEY: "{{ .clerkPublishableKey }}"
        CLERK_SECRET_KEY: "{{ .clerkSecretKey }}"
  data:
    - secretKey: clerkPublishableKey
      remoteRef:
        key: /Lost University Clerk/publishable_key
    - secretKey: clerkSecretKey
      remoteRef:
        key: /Lost University Clerk/credential
