apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: lost-university-route
  namespace: lost-university
spec:
  parentRefs:
    - kind: ListenerSet
      name: lost-university-listeners
      namespace: lost-university
  hostnames:
    - lost.university
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      backendRefs:
        - name: frontend
          port: 80
    - matches:
      - path:
          type: PathPrefix
          value: /api/
      backendRefs:
        - name: backend
          port: 80
---
kind: ListenerSet
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: lost-university-listeners
  namespace: lost-university
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http01-prod
    acme.cert-manager.io/http01-parentreffallback: "true"
spec:
  parentRef:
    name: gateway-shared
    namespace: envoy-gateway-system
  listeners:
    - name: https
      hostname: lost.university
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: lost-university-tls